spring:
    application:
        name: sanshan-monitor
    boot:
        admin:
          routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
          turbine:
            clusters: jscloud
            location: turbine
server:
    port: 8764 #启动端口


eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
           defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  security:
    enabled: false