#  TODO 对Actuator进行定制保护 并且在Spring Security中进行映射保护
# TODO 添加测试模块
management:
    context-path: /actuator
    security:
      enabled: false

info:
  contact:
    email: www.85432173@qq.com
    github: https://github.com/SanShanYouJiu

server:
  servlet-path: /api





