#  TODO 对Actuator进行定制端口保护 并且在Spring Security中进行映射保护
management:
    enabled: true
    shell:
      auth:
        simple:
          user:
            name: admin
            password: 1234567q
    security:
      roles: ADMIN
    context-path: /actuator
    port: 8119


info:
  contact:
    email: sanshanyoujiu@gmail.com
    github: https://github.com/SanShanYouJiu

server:
  servlet-path: /api





