#  TODO 对Actuator进行端口保护
management:
  security:
    enabled: false
  port: 8090

info:
  contact:
    email: sanshanyoujiu@gmail.com
    github: https://github.com/SanShanYouJiu

server:
  servlet-path: /api




