spring:
  application:
    name: sanshan-main
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1

management:
    context-path: /actuator
    security:
      enabled: true

server:
  port: 8060

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true


eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/






