spring:
  application:
    name: sanshan-main

#  TODO 对Actuator进行定制保护 并且在Spring Security中进行映射保护 并且需要对druid的访问进行控制

management:
    context-path: /actuator
    security:
      enabled: true

server:
  port: 8060

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true



eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/






