spring:
    application:
      name: sanshan-auth
    rabbitmq:
      host: ${RABBIT_MQ_HOST:localhost}
      port: ${RABBIT_MQ_PORT:5672}
      username: guest
      password: guest
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      pool:
        max-active: 20
    zipkin:
      enabled: true
    sleuth:
      sampler:
        percentage: 1

server:
    port: 8081 #启动端口


eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
       service-url:
#            defaultZone: http://localhost:8761/eureka/
                defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3

jwt:
  token-header: Authorization
  rsa-secret: c@vbb0}1s{alg3{
  expiration: 7200


client:
  id: sanshan-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret:  23g2@167{ds5