spring:
    application:
      name: sanshan-gate
    rabbitmq:
      host: ${RABBIT_MQ_HOST:localhost}
      port: ${RABBIT_MQ_PORT:5672}
      username: guest
      password: guest
    zipkin:
      enabled: true
    sleuth:
      sampler:
        percentage: 1

server:
  port: 8080 #启动端口
#
zuul:
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    main:
      path: /main/**
      serviceId: sanshan-main

    search:
      path: /search/**
      serviceId: sanshan-search

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


