spring:
    application:
      name: sanshan-gate
    rabbitmq:
      host: ${RABBIT_MQ_HOST:localhost}
      port: ${RABBIT_MQ_PORT:5672}
      username: guest
      password: guest
    zipkin:
      enabled: true
    sleuth:
      sampler:
        percentage: 1

server:
  port: 8080 #启动端口
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    main:
      prefix: /main
      path: /main/**
      serviceId: sanshan-main

    search:
      prefix: /search
      path: /search/**
      serviceId: sanshan-search

    auth:
      prefix: /auth
      path: /auth/**
      serviceId: sanshan-auth

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


auth:
  serviceId: sanshan-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: sanshan-gate  #不填则默认读取spring.application.name
    secret: 123456

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #超时熔断配置为6秒
