spring:
    application:
        name: sanshan-config
    cloud:
      config:
        server:
          git:
            uri: https://gitee.com/SanShanYouJiu/config-repo-demo.git

security:
  user:
    password: 123456

server:
  port: 8750
